apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm_chart.fullname" . }}
  labels:
    {{- include "helm_chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm_chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm_chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm_chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BP_MONGO_SERVICE_TO_CHECK
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm_chart.fullname" . }}
                  key: mongodb-service-to-check
            - name: BP_MONGO_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm_chart.fullname" . }}
                  key: mongodb-connection-string
            - name: BP_MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "mongodb.fullname" . }}
                  key: mongodb-username
            - name: BP_MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongodb
                  key: mongodb-root-password
            - name: BP_MONGO_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm_chart.fullname" . }}
                  key: mongodb-database
            - name: BP_REDIS_SERVICE_TO_CHECK
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm_chart.fullname" . }}
                  key: redis-service-to-check
            - name: BP_REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm_chart.fullname" . }}
                  key: redis-connection-string
            - name: BP_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-redis
                  key: redis-password
          command:
            - ./entrypoint.sh
            - run
          ports:
            - name: http
              containerPort: 1323
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /alive
              port: http
            initialDelaySeconds: 10
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /alive
              port: http
            initialDelaySeconds: 10
            failureThreshold: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
