{{- $release := .Release.Name }}
{{- $ns := .Release.Namespace }}
{{- $domain := .Values.clusterDomain }}
{{- $mongoPort := int .Values.mongodb.service.port }}
{{- $redisPort := int .Values.redis.redisPort }}

{{- $mongoConnectionString := printf "mongodb+srv://%s-mongodb-headless.%s.svc.%s/?ssl=false" $release $ns $domain }}
{{- $mongoServiceToCheck := printf "%s-mongodb-headless.%s.svc.%s:%d" $release $ns $domain $mongoPort }}

{{- $redisConnectionString := printf "%s-redis-master.%s.svc.%s:%d" $release $ns $domain $redisPort }}
{{- $redisServiceToCheck := $redisConnectionString }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm_chart.fullname" . }}
  labels:
    {{- include "helm_chart.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-service-to-check: {{ $mongoServiceToCheck | b64enc | quote }}
  mongodb-connection-string: {{ $mongoConnectionString | b64enc | quote }}
  mongodb-username: {{ print "root" | b64enc | quote }}
  mongodb-database: {{ print "db" | b64enc | quote }}
  redis-service-to-check: {{ $redisServiceToCheck | b64enc | quote }}
  redis-connection-string: {{ $redisConnectionString | b64enc | quote }}
  redis-database: {{ print "0" | b64enc | quote }}
