{{- $mrc := int .Values.mongodb.replicaCount }}
{{- $mpn := int .Values.mongodb.service.port }}
{{- $mfn := include "mongodb.fullname" . }}
{{- $mrn := include "mongodb.namespace" . }}
{{- $mcd := .Values.mongodb.clusterDomain }}
{{- $ml := list }}
{{- range $e, $i := until $mrc }}
{{- $ml = append $ml (printf "%s-%d.%s-headless.%s.svc.%s:%d" $mfn $i $mfn $mrn $mcd $mpn) }}
{{- end }}
{{- $mongoConnectionString := print "mongodb://" (join "," $ml) }}

{{- $rfn := include "redis.fullname" . }}
{{- $rrn := .Release.Namespace }}
{{- $rvcd := .Values.redis.clusterDomain }}
{{- $rrp := int .Values.redis.redisPort }}
{{- $redisConnectionString := printf "%s-master.%s.svc.%s:%d" $rfn $rrn $rvcd $rrp }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm_chart.fullname" . }}
  labels:
    {{- include "helm_chart.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-connection-string: {{ $mongoConnectionString | b64enc | quote }}
  mongodb-username: {{ .Values.mongodb.auth.username | b64enc | quote }}
  mongodb-database: {{ .Values.mongodb.auth.database | b64enc | quote }}
  redis-connection-string: {{ $redisConnectionString | b64enc | quote }}
