{{- $mrc := int .Values.mongodb.replicaCount }}
{{- $mpn := int .Values.mongodb.service.port }}
{{- $mfn := print .Release.Name "-mongodb" }}
{{- $mrn := .Release.Namespace }}
{{- $mcd := .Values.mongodb.clusterDomain }}
{{- $ml := list }}
{{- range $e, $i := until $mrc }}
{{- $ml = append $ml (printf "%s-%d.%s-headless.%s.svc.%s:%d" $mfn $i $mfn $mrn $mcd $mpn) }}
{{- end }}
{{- $mongoConnectionString := print "mongodb://" (join "," $ml) }}
{{- $mongoHostToCheck := printf "%s-%d.%s-headless.%s.svc.%s" $mfn $mrc-1 $mfn $mrn $mcd }}
{{- $mongoPortToCheck := printf "%d" $mpn }}

{{- $rfn := print .Release.Name "-redis" }}
{{- $rrn := .Release.Namespace }}
{{- $rvcd := .Values.redis.clusterDomain }}
{{- $rrp := int .Values.redis.redisPort }}
{{- $redisConnectionString := printf "%s-master.%s.svc.%s:%d" $rfn $rrn $rvcd $rrp }}
{{- $redisHostToCheck := printf "%s-master.%s.svc.%s" $rfn $rrn $rvcd }}
{{- $redisPortToCheck := printf "%d" $rrp }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm_chart.fullname" . }}
  labels:
    {{- include "helm_chart.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-connection-string: {{ $mongoConnectionString | b64enc | quote }}
  mongodb-username: {{ .Values.mongodb.auth.username | b64enc | quote }}
  mongodb-database: {{ .Values.mongodb.auth.database | b64enc | quote }}
  redis-connection-string: {{ $redisConnectionString | b64enc | quote }}
  mongodb-host-to-check: {{ $mongoHostToCheck | b64enc | quote }}
  mongodb-port-to-check: {{ $mongoPortToCheck | b64enc | quote }}
  redis-host-to-check: {{ $redisHostToCheck | b64enc | quote }}
  redis-port-to-check: {{ $redisPortToCheck | b64enc | quote }}
