name: ci

on:
  push:
    branches:
      - master

jobs:
  build_and_push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push 001_postgres_and_redis
        uses: docker/build-push-action@v2
        with:
          context: ./001_postgres_and_redis/app/
          file: ./Dockerfile
          push: true
          tags: akurczyk/blogging_platform:001_postgres_and_redis-latest

      - name: Build and push 002_mysql_and_redis
        uses: docker/build-push-action@v2
        with:
          context: ./002_mysql_and_redis/app/
          file: ./Dockerfile
          push: true
          tags: akurczyk/blogging_platform:002_mysql_and_redis-latest

      - name: Build and push 003_mongo_and_redis
        uses: docker/build-push-action@v2
        with:
          context: ./003_mongo_and_redis/app/
          file: ./Dockerfile
          push: true
          tags: akurczyk/blogging_platform:003_mongo_and_redis-latest
